### ISSUE TITLE
Can't generate image features because model not registered in registry

### ISSUE THREAD

**Issue by soonchangAI** [ronghanghu/vqa-maskrcnn-benchmark-m4c#2]
## ❓ Questions and Help
Hi, I am unable to generate image features using this repo But can generate features for OCR.

Image log:
```
(test) cybertron@cybertron:~$ python mmf/tools/scripts/features/extract_features_vmb.py \
>     --model_name=X-152 \
>     --image_dir=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train/train \
>     --output_folder=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/extracted_features
model and config file exists in directory: /home/cybertron
Traceback (most recent call last):
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 294, in <module>
    feature_extractor = FeatureExtractor()
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 49, in __init__
    self.detection_model = self._build_detection_model()
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 127, in _build_detection_model
    model = build_detection_model(cfg)
  File "/home/cybertron/test_rcnn/vqa-maskrcnn-benchmark-m4c/maskrcnn_benchmark/modeling/detector/detectors.py", line 10, in build_detection_model
    return meta_arch(cfg)
  File "/home/cybertron/test_rcnn/vqa-maskrcnn-benchmark-m4c/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 29, in __init__
    self.backbone = build_backbone(cfg)
  File "/home/cybertron/test_rcnn/vqa-maskrcnn-benchmark-m4c/maskrcnn_benchmark/modeling/backbone/backbone.py", line 43, in build_backbone
    cfg.MODEL.BACKBONE.CONV_BODY
AssertionError: cfg.MODEL.BACKBONE.CONV_BODY: R-152-FPN are not registered in registry
```
OCR log:
```
(test) cybertron@cybertron:~$ python mmf/projects/m4c/scripts/extract_ocr_frcn_feature.py \
>     --detection_cfg=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/detectron_model.yaml \
>     --detection_model=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/detectron_model.pth\
>     --imdb_file=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train.npy \
>     --image_dir=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train \
>     --save_dir=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/ocr_en/extracted_features
Faster R-CNN OCR features
	extracting from /media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train.npy
	saving to /media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/ocr_en/extracted_features
  0%|                                                                                                                  | 0/30 [00:00<?, ?it/s]/home/cybertron/test_rcnn/vqa-maskrcnn-benchmark-m4c/maskrcnn_benchmark/structures/boxlist_ops.py:45: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  keep = ((ws >= min_size) & (hs >= min_size)).nonzero().squeeze(1)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.62it/s]
```
I can generate image features successfully using the tutorial's repo: https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark
But failed to generate image features for OCR.
Image feature log: 
```
(mmf) cybertron@cybertron:~$ python mmf/tools/scripts/features/extract_features_vmb.py \
>     --model_name=X-152 \
>     --image_dir=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train/train \
>     --output_folder=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/extracted_features

model and config file exists in directory: /home/cybertron
/home/cybertron/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)

```
OCR log:
```
(mmf) cybertron@cybertron:~$ python mmf/projects/m4c/scripts/extract_ocr_frcn_feature.py \
>     --detection_cfg=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/detectron_model.yaml \
>     --detection_model=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/detectron_model.pth\
>     --imdb_file=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train.npy \
>     --image_dir=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train \
>     --save_dir=/media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/ocr_en/extracted_features
Faster R-CNN OCR features
	extracting from /media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/defaults/annotations/tiny_train.npy
	saving to /media/cybertron/fa54fcb6-b5e1-492e-978a-6389519c168a/tinyvqa/ocr_en/extracted_features
  0%|                                                                                                                  | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "mmf/projects/m4c/scripts/extract_ocr_frcn_feature.py", line 196, in <module>
    main()
  File "mmf/projects/m4c/scripts/extract_ocr_frcn_feature.py", line 186, in main
    detection_model, image_path, input_boxes=ocr_boxes
  File "mmf/projects/m4c/scripts/extract_ocr_frcn_feature.py", line 103, in extract_features
    output = detection_model(current_img_list, input_boxes=input_boxes)
  File "/home/cybertron/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'input_boxes'

```

**Comment by soumyasj** [comment]
@soonchangAI were you able to extract ocr features?

**Comment by soonchangAI** [comment]
@soumyasj I following steps on https://github.com/facebookresearch/mmf/issues/663#issuecomment-883000371
my command is:
python mmf/projects/m4c/scripts/extract_ocr_frcn_feature.py \
    --detection_cfg=$folder/detectron_model.yaml \
    --detection_model=$folder/detectron_model.pth \
    --imdb_file=$imdb_folder/imdb_test_ocr_en.npy \
    --image_dir=$image_folder/train_val_images \
    --save_dir=$save_folder
